nvidia-settings: Silently ignore the "ToolTips" rc property
Commit 00a066e21290e2853da3b10ae957cd76c913ca3f removed the "ToolTips" rc
property, because most GTK versions no longer support toggling tooltips off and
on in the same way.

However, when running a post-00a066e2 nvidia-settings with an rc file produced
pre-21288711, the new nvidia-settings will print an error:

   ERROR: Error parsing configuration file '/home/aritger/.nvidia-settings-rc' on
      line 11: 'ToolTips = Yes' (Unrecognized attribute name).

Update nvidia-settings to silently ignore the "ToolTips" property, rather than
complain about it.